# Generated by Django 3.1.1 on 2020-09-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polzovatel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ref_date', models.DateTimeField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
