# Generated by Django 3.1.1 on 2020-09-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polzovatel',
            old_name='ref_date',
            new_name='reg_date',
        ),
    ]
