# Generated by Django 3.1.1 on 2020-10-01 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200922_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('doctor_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='polzovatel',
            name='fav_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.hospital'),
        ),
    ]
